repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.6.1
    hooks:
      - id: betterleaks
